### ISSUE TITLE
Chapter 12 Using Spring Remoting -- Section: Spring Boot Artemis Starter

### ISSUE THREAD

**Issue by fangtasticmrz** [Apress/pro-spring-5#32]
The code sample in this section doesn't seem to work (boot-jms). And seems it's complaining about the JTA is not set. I have tried a couple of things but couldn't make it work, please check. Thanks!

_Exception in thread "main" org.springframework.jms.UncategorizedJmsException: Uncategorized exception occurred during JMS processing; nested exception is com.atomikos.jms.AtomikosTransactionRequiredJMSException: The JMS session you are using requires a JTA transaction context for the calling thread and none was found.
Please correct your code to do one of the following: 
1. start a JTA transaction if you want your JMS operations to be subject to JTA commit/rollback, or
2. increase the maxPoolSize of the AtomikosConnectionFactoryBean to avoid transaction timeout while waiting for a connection, or
3. create a non-transacted session and do session acknowledgment yourself, or
4. set localTransactionMode to true so connection-level commit/rollback are enabled.
	at org.springframework.jms.support.JmsUtils.convertJmsAccessException(JmsUtils.java:311)
	at org.springframework.jms.support.JmsAccessor.convertJmsAccessException(JmsAccessor.java:185)
	at org.springframework.jms.core.JmsTemplate.execute(JmsTemplate.java:507)
	at org.springframework.jms.core.JmsTemplate.send(JmsTemplate.java:584)
	at org.springframework.jms.core.JmsTemplate.convertAndSend(JmsTemplate.java:661)
	at com.apress.prospring5.ch12.Application.main(Application.java:46)
Caused by: com.atomikos.jms.AtomikosTransactionRequiredJMSException: The JMS session you are using requires a JTA transaction context for the calling thread and none was found.
Please correct your code to do one of the following: 
1. start a JTA transaction if you want your JMS operations to be subject to JTA commit/rollback, or
2. increase the maxPoolSize of the AtomikosConnectionFactoryBean to avoid transaction timeout while waiting for a connection, or
3. create a non-transacted session and do session acknowledgment yourself, or
4. set localTransactionMode to true so connection-level commit/rollback are enabled.
	at com.atomikos.jms.AtomikosTransactionRequiredJMSException.throwAtomikosTransactionRequiredJMSException(AtomikosTransactionRequiredJMSException.java:23)
	at com.atomikos.jms.ConsumerProducerSupport.enlist(ConsumerProducerSupport.java:90)
	at com.atomikos.jms.AtomikosJmsMessageProducerProxy.send(AtomikosJmsMessageProducerProxy.java:34)
	at org.springframework.jms.core.JmsTemplate.doSend(JmsTemplate.java:634)
	at org.springframework.jms.core.JmsTemplate.doSend(JmsTemplate.java:608)
	at org.springframework.jms.core.JmsTemplate.lambda$send$3(JmsTemplate.java:586)
	at org.springframework.jms.core.JmsTemplate.execute(JmsTemplate.java:504)
	... 3 more_

**Comment by iuliana** [comment]
Hello @fangtasticmrz, 

Something must be wrong on your local environment. I just run the `com.apress.prospring5.ch12.Application#main(..)`  and it runs fine. 

Proof: 
![jms-proof](https://user-images.githubusercontent.com/2484724/132409614-bda3d6df-f0c5-4406-8a9b-7587c7ac4584.png)

Using the Spring Boot JMs starter should ensure a default configuration for JTA. If I pause the execution and inspect the beans in my context, I see the JTA beans present. 

![jta-proof](https://user-images.githubusercontent.com/2484724/132410823-62cfd2c2-c18a-43bc-b7bd-c2515313770c.png)

So, please check your local environment and changes you might have done, because the code works as intended. 

Cheers, 
Iuliana Cosmina
